import React from "react";
import Head from "next/head";
import type { NextPage } from "next";
import { useMutation, useQuery } from "react-query";

import { Container } from "@/components/container";
import { TournamentService } from "@/services/tournaments";
import { queryClient } from "@/pages/_app";

const Home: NextPage = () => {
  const tournaments = useQuery("tournaments", () =>
    TournamentService.getAll({
      state: "all",
    })
  );
  const create = useMutation(TournamentService.create, {
    onSuccess: () => queryClient.invalidateQueries("tournaments"),
  });

  return (
    <>
      <Head>
        <title>Avion School Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <h1 className="text-center mt-4 text-2xl font-semibold">Tournaments</h1>

        <button
          type="button"
          onClick={() => {
            create.mutate({
              "tournament[name]": "Test Tournament 2",
              "tournament[description]": "Test Tournament 2",
              "tournament[open_signup]": true,
              "tournament[tournament_type]": "single elimination",
            });
          }}
        >
          Create Tournament
        </button>

        {tournaments.data ? (
          <ul>
            {tournaments.data.map(({ tournament }) => (
              <li key={tournament.id}>
                <a
                  href={tournament.full_challonge_url}
                  target="_blank"
                  rel="noreferrer"
                >
                  {tournament.name} - {tournament.state}
                </a>
              </li>
            ))}
          </ul>
        ) : (
          <p>Loading...</p>
        )}
      </Container>
    </>
  );
};

export default Home;
